_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 30
                - 41
                - 49
                - 51
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.2
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
